project:
  type: website

website:
  page-navigation: true
  title: "VAA Team 6"
  site-url: "https://isss608g.netlify.app/"
  
  favicon: images/favicon.png
  
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Honglu & Kaixin"
  
  navbar:
    left:
      - href: proposal.qmd
        text: Proposal
      - href: poster.qmd
        text: Poster
      - href: https://isss608g.shinyapps.io/vaagroup/
        text: Shiny App
      - href: guide.qmd
        text: User Guide
        
    right: 
      - href: about.qmd
        text: About Us

format:
  html:
    smooth-scroll: true
    theme: 
      - flatly
      - styles.css
    css: styles.css
    toc: true

editor: visual

